---
- hosts: localhost
  tasks:
    - add_host: name="{{ item }}" groups="devstack_nodes,devstack_controller"
      with_items: "{{ groups.controller }}"
    - add_host: name="{{ item }}" groups="devstack_nodes,devstack_computes"
      with_items: "{{ groups.computes }}"

- hosts: devstack_nodes
  roles:
    - stack/devstack/prep

- hosts: devstack_controller
  roles:
    - stack/devstack/install-controller

- hosts: devstack_computes
  roles:
    - stack/devstack/install-compute

- hosts: devstack_controller
  roles:
    - stack/devstack/postinstall
