---
- include: "{{ item }}"
  with_first_found:
    - files:
      - "nova_packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "nova_packages_{{ ansible_distribution|lower }}.yml"
      - "nova_packages_{{ ansible_os_family|lower }}.yml"
      skip: true

- include: disable_virbr0.yml
  become: true
  become_user: root

- name: Install nova configuration
  template: src="nova.conf" dest="/etc/nova/nova.conf"
  when: inventory_hostname not in groups.openstack_controller

- name: Install nova-compute configuration
  template: src="nova-compute.conf" dest="/etc/nova/nova-compute.conf"

- name: Start nova services
  service: name="{{ item }}" state="started"
  with_items:
    - libvirt-bin
    - nova-compute
