---
- name: Stop Web Server
  become: true
  become_user: root
  service: name="apache2" state="stopped"

- name: Make sure webserver stopped completely
  wait_for: port=80 state=stopped

- name: Start Web Server
  become: true
  become_user: root
  service: name="apache2" state="started"
