apiVersion: v1
kind: Pod
metadata:
  name: nginx-backend
  labels:
    app: nginx
    owner: t1
    tier: backend
spec:
  containers:
  - name: nginx
    image: rstarmer/nginx-curl
    ports:
    - containerPort: 80
