---
- name: Install Keystone WSGI configuration
  copy: src="debian/wsgi-keystone.conf" dest="/etc/apache2/sites-available/wsgi-keystone.conf"
  register: wsgi

- name: Activate Keystone WSGI configuration
  file: src="/etc/apache2/sites-available/wsgi-keystone.conf" dest="/etc/apache2/sites-enabled/wsgi-keystone.conf" state="link"
  when: wsgi.changed
